### ISSUE TITLE
sora ios sdkでアプリ実行時に dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib のエラー

### ISSUE THREAD

**Issue by kobatako** [shiguredo/sora-ios-sdk#1]
sora ios sdkでexampleを試させていただいてるんですが、ビルド後、実行するときにエラーが出てしまいます。下記がエラー内容になります。
```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /private/var/containers/Bundle/Application/032EF254-6D6F-4F84-BDC0-B9FD1C9D1ECD/SoraApp.app/Frameworks/Sora.framework/Sora
  Reason: Incompatible library version: Sora requires version 1.0.0 or later, but libswiftAVFoundation.dylib provides version 0.0.0
```

Carthageでのライブラリのインストールに問題があるかもしれません。
参考までにCarthageのコマンドになります。
```
carthage update --platform iOS
```

こちらが今ビルドしている環境情報とバージョン情報になります
```
OS: mac Sierra 10.12.4
xcode: 8.3.1
swift : 3.0.1
ios: 10.1
```

sora ios sdkのセットアップページで一からセットアップしたりしているのですが、
結局同じエラーが出てしまって解決できませんでした。
下記が参考にしたページになります。
https://sora.shiguredo.jp/ios-sdk-doc/setup.html

お忙しいところ恐縮ですが、回答の程よろしくお願いいたします。

**Comment by szktty** [comment]
```
Reason: Incompatible library version: Sora requires version 1.0.0 or later, but libswiftAVFoundation.dylib provides version 0.0.0
```

このエラーは Sora のビルドに使用した Swift のバージョンとプロジェクトで使用する Swift のバージョンが異なる場合に発生するようです。こちらの環境 (OSX 10.12.4, Xcode 8.3.1, Swift 3.1, iOS 10.3.1) では同様のエラーを確認できませんでしたが、可能であれば次の方法をお試しください。

- Sora.framework をソースコードからビルドする (``carthage update --no-use-binaries`` を使うか、もしくはソースコードをリポジトリからクローンしてビルドします)
- 開発環境と iOS を最新版にアップデートする

**Comment by kobatako** [comment]
swiftのバージョンを3.1にしたらできました。
ただ、carthegeでのビルドに毎回失敗して結局、xcodeからビルドしたものを使用しました。
その他のSocketRoketもcarthegeではうまくビルドできず、sora ios sdk内のものを使用したら
ビルドすることができました。

ありがとうございました。
