### ISSUE TITLE
マイク音声の配信のオンオフ方法

### ISSUE THREAD

**Issue by iPre-Innovate** [shiguredo/sora-ios-sdk#10]
マイク音声の配信オンオフ方法について
もし可能であればご教授ください

やりたいことは、映像音声配信途中でマイクを機能停止させるのではなく、マイク音声の配信をON/OFF
したいです

1.xでは`mediaPublisher.mainMediaStream.nativeAudioTrack.isEnabled`に`true/false`を設定することでやっていましたが

2.xでは上記が使えないため以下を含め調べていますがうまくいきません
- AVAudioSession
- AVCaptureDevice

マイクのオンオフの都度`Configuration.audioEnabled`を変更して`Sora.shared.connect()`で再コネクトするべきでしょうか？

よろしくお願いします

### 環境
- Sora iOS SDK: 2.0.0
- Mac OS X : 10.12.6
- Xcode: 9.1
- Swift: 4.0
- iOS: 11.1.1
- Carthage: 0.26.2

**Comment by szktty** [comment]
@iPre-Innovate 申し訳ありません、 2.0.0 に配信を停止・再開する機能がなありませんでした。機能を追加した 2.0.1 をリリースしました。

音声の配信を停止するには、 ``MediaStream`` の  ``audioEnabled`` プロパティに ``false`` を指定します。マイクの動作は停止しません。

詳しくは下記のドキュメントをご覧下さい。

- https://sora.shiguredo.jp/ios-sdk-doc/devguide.html#id18
- https://sora.shiguredo.jp/ios-sdk-doc/devguide.html#id25

**Comment by iPre-Innovate** [comment]
ご早い対応ありがとうございます
