### ISSUE TITLE
iTunesにアップロード時にshiguredo/SDWebImageに関してエラーがでる

### ISSUE THREAD

**Issue by iPre-Innovate** [shiguredo/sora-ios-sdk#12]
Sora iOS SDKにて開発する際に、ドキュメントにあるように以下にCarthageファイルを作成しています
```
github "shiguredo/sora-ios-sdk" "2.0.2"
github "shiguredo/sora-webrtc-ios" "62.12.1"
github "shiguredo/SocketRocket" "0.5.1-carthage.1"
github "shiguredo/SDWebImage" "4.0.0"
```

しかし作成したアプリをiTunesに登録する際に以下に登録エラーが出ます
```
This bundle Payload/xxxxx.app/Frameworks/SDWebImage.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion.
```

対処として、`SDWebImage.framework`内の`info.plist`のVersion項目に何も値が設定されてないので
値（1などを）を記入しています。

Carthageアップグレードをする度に同様のことをしないといけないので面倒です
対処いただくことは可能でしょうか？

 # 環境
- Sora iOS SDK: 2.0.2
- Mac OS X : 10.12.6
- Xcode: 9.2
- Swift: 4.0
- iOS: 11.2
- Carthage: 0.26.2

**Comment by szktty** [comment]
次のリリースで SDWebImage のバージョンを上げて対処する予定です。リリースしたらお知らせしますので、しばらくお待ちください。

**Comment by iPre-Innovate** [comment]
確認遅くなりました
ご対応ありがとうございます
次期バージョンお待ちしています
