### ISSUE TITLE
Swift 4.1 への対応

### ISSUE THREAD

**Issue by voluntas** [shiguredo/sora-ios-sdk#15]
Xcode 9.3 がリリースされたので、対応する Swift のバージョンを 4.0 から 4.1 へ上げる。

**Comment by akisute** [comment]
feature/update-swift-4.1 ブランチにて作業.

基本的にはやること殆どないが,

- Xcode 9.3で再ビルド, バイナリをSwift 4.1の状態にして上げ直し
- Xcode 9.2/Swift 4.0についてはソースコードビルドにより対応可能であることを明記する

```
carthage update --platform iOS --no-use-binaries
```

**Comment by akisute** [comment]
https://shiguredo.kibe.la/shared/entries/20794178-62e9-42d1-8870-63ab1d1f2713
に作業内容がまとめられているので従えば良さそう

**Comment by voluntas** [comment]
2.1.1 で対応済み。
