### ISSUE TITLE
ロール`recvonly` に設定している場合、ストリームの設定 `remoteAudioVolume` が反映されない

### ISSUE THREAD

**Issue by Kotaro666-dev** [shiguredo/sora-ios-sdk#150]
# 概要

クライアントの設定項目のうち、ロールを `recvonly` に設定した場合、受信したストリームの設定 `remoteAudioVolume` が反映されません。

ロール `subscriber` が `recvonly` に置き換えられて deprecated になった後に、`remoteAudioRemote` の setter メソッド内の条件が `subscriber` から `recvonly` に変更されていないことが原因ではないでしょうか？

# 動作テストした結果

ロールを `recvonly` から `subscriber` に変更した状態で確認すると、受信したストリームから音声が出力されていないことを確認しました。
そのため、deprecated となっている `subscriber` では、ストリームの設定 `remoteAudioVolume` が正常に動作していることを確認できました。

# 補足説明

## クライアントの設定例

私の実装では以下のようにクライアントの設定を行いました。

```
var config = Configuration(
        url: myUrl,
        channelId: myChannelId ,
        role: .recvonly,
        multistreamEnabled: true)
```

## `remoteAudioRemote` の説明

ソースコードでは、以下のように記載されていることを確認しました。
コメント文にも deprecated となった「サブスクライバー」という表記があります。

```
    /**
     受信した音声のボリューム。 0 から 10 (含む) までの値をセットします。
     このプロパティはロールがサブスクライバーの場合のみ有効です。
     */
    var remoteAudioVolume: Double? { get set }
```

## subscriber が recvonly に置き換えられたこと

ソースコードでは、`subscriber` が `recvonly` に置き換えられて、deprecated となったことを確認しました。

```
/// この列挙子は recvonly に置き換えられました。
    @available(*, deprecated, renamed: "recvonly",
               message: "この列挙子は recvonly に置き換えられました。")
    case subscriber
```

**Comment by voluntas** [comment]
@Kotaro666-dev discord での相談がないため閉じます。README に掲載しているとおりまずは以下をご確認ください。 https://github.com/shiguredo/oss
