### ISSUE TITLE
接続が出来ない問題の質問

### ISSUE THREAD

**Issue by koyama** [shiguredo/sora-ios-sdk#2]
バージョンは 0.2.0です
実URLは伏せてあります

Sora FrameworkのConnectionを作りPublisherをconnectしたところ、下記のような状態でconnection timeoutが発生します。

```
[wss://dev-20170424082558fde08ed6697.example.com:1935/signaling b96411d1 2017-04-24 20:43:39] MediaPublisher: try connect
[wss://dev-20170424082558fde08ed6697.example.com:1935/signaling b96411d1 2017-04-24 20:43:39] PeerConnection: connect
[wss://dev-20170424082558fde08ed6697.example.com:1935/signaling b96411d1 2017-04-24 20:43:40] WebSocket: open wss://dev-20170424082558fde08ed6697.example.com:1935/signaling
[wss://dev-20170424082558fde08ed6697.example.com:1935/signaling b96411d1 2017-04-24 20:44:10] PeerConnection: timeout connecting
[wss://dev-20170424082558fde08ed6697.example.com:1935/signaling b96411d1 2017-04-24 20:44:10] Signaling: terminate all connections
[wss://dev-20170424082558fde08ed6697.example.com:1935/signaling b96411d1 2017-04-24 20:44:10] MediaPublisher: connect error: The operation couldn’t be completed. (Sora.ConnectionError error 6.)
[wss://dev-20170424082558fde08ed6697.example.com:1935/signaling b96411d1 2017-04-24 20:44:10] PeerConnection: terminate
(lldb) po error
Sora.ConnectionError.connectionWaitTimeout


(lldb)
```

Webにてアクセス下際は正常に閲覧可能であり、Soraのフレームワークに付属しているサンプルアプリでも発生しているのですが、原因をご教示頂けますでしょうか

また、最新バージョンでは以下の通りとなりました
ws(sslなし）、ベーシック認証等の有無も検証しましたが、状況は同じようです。

Framework付属のサンプルソースでも検証していますが同様の結果となりました。

```
[wss://dev-201704260520590058336c4b2.example.com:1935/signaling 13ea5d8f 2017-04-26 17:40:14] MediaPublisher: try connect
[wss://dev-201704260520590058336c4b2.example.com:1935/signaling 13ea5d8f 2017-04-26 17:40:14] PeerConnection: connect
[wss://dev-201704260520590058336c4b2.example.com:1935/signaling 13ea5d8f 2017-04-26 17:40:14] WebSocket: open wss://dev-201704260520590058336c4b2.example.com:1935/signaling
2017-04-26 17:41:30.129403+0900 SoraApp[349:210006] [] nw_connection_get_connected_socket_block_invoke 1 Connection has no connected handler
[wss://dev-201704260520590058336c4b2.example.com:1935/signaling 13ea5d8f 2017-04-26 17:41:30] WebSocket: fail: The operation couldn’t be completed. Operation timed out
[wss://dev-201704260520590058336c4b2.example.com:1935/signaling 13ea5d8f 2017-04-26 17:41:30] Signaling: begin terminate all connections
[wss://dev-201704260520590058336c4b2.example.com:1935/signaling 13ea5d8f 2017-04-26 17:41:30] ConnectionMonitor: validate connection state
[wss://dev-201704260520590058336c4b2.example.com:1935/signaling 13ea5d8f 2017-04-26 17:41:30] PeerConnection: finish termination
[wss://dev-201704260520590058336c4b2.example.com:1935/signaling 13ea5d8f 2017-04-26 17:41:30] MediaPublisher: connect error: The operation couldn’t be completed. (Sora.ConnectionError error 7.)
[wss://dev-201704260520590058336c4b2.example.com:1935/signaling 13ea5d8f 2017-04-26 17:41:30] PeerConnection: terminate
The operation couldn’t be completed. (Sora.ConnectionError error 7.)
```

**Comment by szktty** [comment]
まずは次の開発環境のバージョンを教えて頂けますでしょうか？ 次の項目についてお願いします。

- Sora iOS SDK
- Mac OS X
- Xcode
- Swift
- iOS

ログを見る限りでは WebSocket の接続に失敗しているようです。サーバーが見つからずにタイムアウトになっていると思われるので、 URL とポート番号を確認してください。

二つ目のログも同じ原因と思われますが、途中で出力される ``nw_connection_get_connected_socket_block_invoke 1 Connection has no connected handler`` については現在原因を調査中です。

**Comment by koyama** [comment]
頂きました内容について以下に記載します

Sora iOS SDK 1.0.0
Mac OS X sierra
Xcode 8.3
Swift 3.1
iOS 10

よろしくお願いします

**Comment by szktty** [comment]
> Sora iOS SDK 1.0.0
Mac OS X sierra
Xcode 8.3
Swift 3.1
iOS 10

マイナーバージョンとメンテナンスバージョンも含めて (Mac OS X 10.12.4 など) お願いします。

先にコメントした URL とポート番号の確認はされましたでしょうか？

**Comment by koyama** [comment]
すべて現時点での最新となっております
また、URLとポート番号については、Web,JS側で動作確認出来たものを利用しておりますので、間違いは無いかと思われます

**Comment by voluntas** [comment]
@koyama wscat や https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo?hl=ja などを利用して、WebSocket に繋がるか確認いただけますでしょうか。今のところ WebSocket が接続できていないという判断できない状況です。

wscat であれば

```
$ wscat --connect  wss://dev-20170424082558fde08ed6697.example.com:1935/signaling
```

にて繋がるかどうかの確認が可能です。よろしくお願いいたします。問題なければ

```
connected (press CTRL+C to quit)
```

が表示されます。

**Comment by koyama** [comment]
---wscatで接続確認
wscat --connect wss://dev-2017042803005902da62a52c2.example.com:1935/signaling
error: Error: connect ETIMEDOUT 11.111.11.111:1935



試しにですが、httpでの確認もしてみましたところ、
Sora.Connection(URL:
            URL(string: "https://dev-2017042804555902f55701f1b.example.com/signaling")!, mediaChannelId: "3b588ba8")
エラー内容が変わりました。
接続まではできているようですが、その後、error code 1と3が繰り返さえるようです。
以下にログを記載致します

[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:18] MediaPublisher: try connect
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:18] PeerConnection: connect
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:18] WebSocket: open https://dev-2017042804555902f55701f1b.example.com/signaling
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:19] ConnectionMonitor: validate connection state
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:19] WebSocket: opened
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:19] Signaling: connected
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:19] PeerConnection: create peer connection
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:19] PeerConnection: create media capturer
2017-04-28 17:49:19.944905+0900 SoraApp[517:450458] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-04-28 17:49:19.949187+0900 SoraApp[517:450458] [MC] Reading from public effective user settings.
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] PeerConnection: video capturer track ID: capturer_0
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] PeerConnection: audio capturer track ID: capturer_1
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] PeerConnection: should negatiate
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] MediaPublisher: add media stream 'mainStream'
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] Signaling: send connect message: ["channel_id": "3b588ba8", "role": "upstream", "type": "connect"]
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] WebSocket: send message (state signalingConnected): {"channel_id":"3b588ba8","role":"upstream","type":"connect"}
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] WebSocket: send message as JSON: {"channel_id":"3b588ba8","role":"upstream","type":"connect"}
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] WebSocket: close: code 1001, reason Stream end encountered, clean false
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] Signaling: begin terminate all connections
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] PeerConnection: ICE connection state changed: closed
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] PeerConnection: ICE gathering state changed: complete
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] PeerConnection: signaling state changed: closed
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] ConnectionMonitor: validate connection state
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] PeerConnection: finish termination
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] MediaPublisher: connect error: The operation couldn’t be completed. (Sora.ConnectionError error 1.)
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:20] PeerConnection: terminate
The operation couldn’t be completed. (Sora.ConnectionError error 1.)
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] MediaPublisher: try connect
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: connect
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] WebSocket: open https://dev-2017042804555902f55701f1b.example.com/signaling
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] WebSocket: opened
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] Signaling: connected
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: create peer connection
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: create media capturer
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: use shared media capturer
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: video capturer track ID: capturer_0
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: audio capturer track ID: capturer_1
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: should negatiate
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] MediaPublisher: add media stream 'mainStream'
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] Signaling: send connect message: ["channel_id": "3b588ba8", "role": "upstream", "type": "connect"]
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] WebSocket: send message (state signalingConnected): {"channel_id":"3b588ba8","role":"upstream","type":"connect"}
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] WebSocket: send message as JSON: {"channel_id":"3b588ba8","role":"upstream","type":"connect"}
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] WebSocket: close: code 4490, reason DUPLICATED-CHANNEL-ID, clean true
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] Signaling: begin terminate all connections
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: ICE connection state changed: closed
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: ICE gathering state changed: complete
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: signaling state changed: closed
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] ConnectionMonitor: validate connection state
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: finish termination
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] MediaPublisher: connect error: The operation couldn’t be completed. (Sora.ConnectionError error 3.)
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:31] PeerConnection: terminate
The operation couldn’t be completed. (Sora.ConnectionError error 3.)
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] MediaPublisher: try connect
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: connect
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] WebSocket: open https://dev-2017042804555902f55701f1b.example.com/signaling
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] WebSocket: opened
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] Signaling: connected
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: create peer connection
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: create media capturer
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: use shared media capturer
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: video capturer track ID: capturer_0
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: audio capturer track ID: capturer_1
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: should negatiate
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] MediaPublisher: add media stream 'mainStream'
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] Signaling: send connect message: ["channel_id": "3b588ba8", "role": "upstream", "type": "connect"]
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] WebSocket: send message (state signalingConnected): {"channel_id":"3b588ba8","role":"upstream","type":"connect"}
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] WebSocket: send message as JSON: {"channel_id":"3b588ba8","role":"upstream","type":"connect"}
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] WebSocket: close: code 1001, reason Stream end encountered, clean false
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] Signaling: begin terminate all connections
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: ICE connection state changed: closed
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: ICE gathering state changed: complete
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: signaling state changed: closed
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] ConnectionMonitor: validate connection state
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: finish termination
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] MediaPublisher: connect error: The operation couldn’t be completed. (Sora.ConnectionError error 1.)
[https://dev-2017042804555902f55701f1b.example.com/signaling 3b588ba8 2017-04-28 17:49:45] PeerConnection: terminate
The operation couldn’t be completed. (Sora.ConnectionError error 1.)


また、更に試しにですが、
mediaSubscriberをconnectしてみたところ、映像の送受信が確認ができました。
前述のエラーはmediaPublisherのものになります。

**Comment by voluntas** [comment]
まずは WebSocket の接続が問題なくできていることを確認したいと考えております。

> wscat --connect wss://dev-2017042803005902da62a52c2.example.com:1935/signaling
> error: Error: connect ETIMEDOUT 11.111.11.111:1935

こちらの URL では WebSocket に正常に接続できないようですので、 URL やポートの確認をお願いします。
wscat で connected がでないとこの URL には正常に接続できないため、 SDK でも接続ができません。

wscat を利用して connected の出ている状態を、確認お願いできますでしょうか。

**Comment by szktty** [comment]
@koyama 時間が空きましたので一旦閉じます。また何かありましたら新しい issue の作成をお願いします。
