### ISSUE TITLE
iOS12対応について

### ISSUE THREAD

**Issue by daihase** [shiguredo/sora-ios-sdk#24]
現在こちらのSDKを用いてサービスの方展開しており、
そろそろ正式にリリースされるであろうiOS12での稼働状況がどのようになっているかを確認したいです。
（正式にiOS12がリリースされても現状のSDK(ver 2.1.3)を組み込んだ状態で問題なく使用できるかどうか）

iOS12リリース後に当サービスを利用したユーザーから、SDKを用いたライブ面談機能がつかえなくなった、といった状況を避けたいと考えており、この辺り状況の方お分かりでしたらご共有頂けると幸いです。
宜しくお願い致します。

**Comment by voluntas** [comment]
@daihase 現段階で iOS 12 での動作確認はまだ行っておりません。もし可能であれば、iOS 12 public beta で確認していただき動作するかどうかの報告を頂ければ助かります。

**Comment by voluntas** [comment]
@daihase 大変たすかります。弊社側でも他の作業が落ち着き次第、動作確認を進めてまいります。

**Comment by voluntas** [comment]
@daihase ご報告ありがとうございます、本当に感謝します！弊社側でも確認したらこちらの issues に報告させていただきクローズさせていただこうと思います。

**Comment by hkk** [comment]
Xcode Version 10.0 でビルドした際に以下のエラーが出ているようです。

Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /〜/Pods/Sora/Carthage/Build/iOS/Sora.framework/Modules/Sora.swiftmodule/arm.swiftmodule

Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /〜/Pods/Sora/Carthage/Build/iOS/Sora.framework/Modules/Sora.swiftmodule/arm64.swiftmodule

CocoaPods を利用しており、ソースコードからビルドは試していません。
どうぞよろしくお願いいたします。

**Comment by szktty** [comment]
@hkk Xcode 10 で Swift のバージョンが 4.2 に上がったことが原因だと思われます。 Carthage/CocoaPods でダウンロードできる Sora iOS SDK のバイナリは Swift 4.1.2 でビルドしてあり、 4.1 と 4.2 ではバイナリ互換性がないのでビルドに失敗します。

現在、 Swift 4.2 への対応作業を進めています。対応次第アップデートをリリースしますので、しばらくお待ちください。

**Comment by szktty** [comment]
@daihase @hkk iOS 12 / Xcode 10 / Swift 4.2 に対応したバージョン 2.2.0 をリリースしました。お待たせして大変申し訳ありません。主な変更は以下を参照して下さい。
https://github.com/shiguredo/sora-ios-sdk/blob/master/CHANGES.md

**Comment by daihase** [comment]
@szktty 
ご連絡の方ありがとうございます、こちら大変助かります！
早速活用させていただきたいと思います。
