### ISSUE TITLE
metadata のデータ形式について

### ISSUE THREAD

**Issue by FromAtom** [shiguredo/sora-ios-sdk#27]
Sora iOS SDKにて定義されている `struct Configuration` の `public var metadata: String?` について質問です。

JavaScript SDKではここにセットされたJSON形式の文字列が、サーバサイドでJSONとして認識されパーズされるのですが、iOS SDKでは文字列のままサーバサイドに到達します。そのため、metadataを用いた認証処理が正常に動かないため、サーバサイドでは

```ruby
if params[:metadata].is_a?(String)
    # iOS SDKから送られるmetadataはStringになっているのでJSONとしてパーズする
    metadata = JSON.parse(params[:metadata], symbolize_names: true)
elsif params[:metadata].is_a?(Hash)
    # Web SDKから送られるmetadataはHashになっているのでそのまま使う
    metadata = params[:metadata]
else
    return ''
end
```

といった対応コードを書いています。iOS SDKでは文字として送られ、JavaScript SDKではJSONにパーズできる形で送られるのは仕様なのでしょうか？それとも、iOSクライアントサイドで行う処理が抜け落ちているのでしょうか？

**Comment by szktty** [comment]
@FromAtom 現時点では文字列として扱うという仕様になってしまっているため、サーバーサイドでの調整をお願いします。

現在 JavaScript SDK の挙動に合わせられるよう、各 SDK での metadata の扱いの見直しを進めています。お手数をおかけしますが、 API 変更のリリースまで SDK ごとに処理を分けて頂けると助かります。

ご迷惑をおかけして申し訳ありません。

**Comment by FromAtom** [comment]
@szktty なるほど、サーバサイドで対応するのが正解だと分かって良かったです。ご返答いただきありがとうございました。
