### ISSUE TITLE
carthage build failed

### ISSUE THREAD

**Issue by U-SOFTFACTORY** [shiguredo/sora-ios-sdk#3]
---問題点---
https://sora.shiguredo.jp/ios-sdk-doc/setup.html
の手順通り、carthegに下記を設定し、updateしたところ
互換性のないバージョンとなりエラーが発生し、
unboxとsora-ios-sdkが利用できません。

---環境---
macOS Sierra
Version 8.3.2 (8E2002)

-- cartfile --
github "shiguredo/sora-ios-sdk" "1.0.0"
github "shiguredo/sora-webrtc-ios" "57.0"
github "facebook/SocketRocket" "0.4.2"
github "johnsundell/unbox" "2.2.1"

--- carthage update log ---

```
*** Downloading sora-ios-sdk.framework binary at "1.0.0"
*** Downloading sora-webrtc-ios.framework binary at "M57"
*** Downloading SocketRocket.framework binary at "0.4.2"
*** Checking out unbox at "2.2.1"
*** Skipped installing sora-ios-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.0.2 and the local version is 3.1."
*** Checking out sora-ios-sdk at "1.0.0"
*** xcodebuild output can be found in /var/folders/pk/nkv_60cd629g28km03t35ypm0000gn/T/carthage-xcodebuild.mkQRsi.log
*** Building scheme "Sora" in Sora.xcodeproj
```

**Comment by szktty** [comment]
@U-SOFTFACTORY Swift 3.1 でビルドしたバイナリを用意しました。バージョンを上げましたので、 Cartfile の Sora iOS SDK のバージョンを次のように書き換えてください。

```
github "shiguredo/sora-ios-sdk" "1.0.1"
```

もしくはバイナリを使わずにソースコードからビルドする方法があります。 Carthage のオプションに --no-use-binaries を指定するか、もしくは Carthage のバージョンが 0.20.0 以前であれば、最新版にアップデートすると Swift のバージョンに差異がある場合にソースコードからビルドするはずです。詳しくは Carthage のドキュメントを参考にしてください。

**Comment by voluntas** [comment]
@U-SOFTFACTORY こちらいかがでしょうか。一度閉じさせていただきます。問題があれば再度オープンしていただければと思います。
