### ISSUE TITLE
シミュレーターでのビルドについて

### ISSUE THREAD

**Issue by FromAtom** [shiguredo/sora-ios-sdk#30]
現在Sora iOS SDKはシミュレータに非対応であると明記されているのですが、できればシミュレーターでもビルド・実行が可能にならないでしょうか。既存のアプリにSora iOS SDKを組み込んだ場合、配信に関係しない機能開発をする際にも実機でのデバッグが強制されてしまう点が不便に感じております。また、テストやCIなどでも不便な点が多いです。

シミュレータでSoraSDKを使いたいわけではなく、ReplayKit、カメラ、Push通知のようにビルドはできてアプリを実行はできるが該当機能は利用できない状態になるととても助かります。技術的に困難な点があるかとは思いますが、ぜひご一考くだされば幸いです。

**Comment by szktty** [comment]
@FromAtom ご不便をおかけして申し訳ありません。非サポートになりますが、シミュレーター用のバイナリを含めてのリリースについて調査します。少々お待ち頂けると幸いです。

**Comment by FromAtom** [comment]
@szktty ありがとうございます。よろしくお願いいたします。

**Comment by szktty** [comment]
@FromAtom お待たせして申し訳ありません。シミュレーターでのビルドと実行が可能なバージョンをリリースしました。バージョンは 2.4.1 です。シミュレーター上の動作は保証できませんので、 WebRTC に関する処理のデバッグは実機をお使いください。

今回のリリースから、 WebRTC ライブラリを配布するリポジトリが https://github.com/shiguredo/sora-webrtc-ios から https://github.com/shiguredo/shiguredo-webrtc-ios に変わりました。以前のバージョンのバイナリにはシミュレーター向けのアーキテクチャが含まれていませんので、 Cartfile/Podfile の修正をお願いします。

Cartfile/Podfile での指定については、こちらのドキュメントもご確認ください 。 -> https://sora.shiguredo.jp/ios-sdk-doc/setup.html#xcode

**Comment by FromAtom** [comment]
ご対応いただきありがとうございます！大変助かります！
