### ISSUE TITLE
multistream配信時のsendonlyパラメータへの対応に関して

### ISSUE THREAD

**Issue by soudegesu** [shiguredo/sora-ios-sdk#33]
Sora `19.10.3` から実験的機能として追加された `multistream` の `sendonly` パラメータにご対応いただけないでしょうか。

iOSにてスクリーンのブロードキャスト機能の実装に利用する `Broadcast Upload Extension` では、利用可能なメモリの上限が厳しく設定されており、既にmultistreamで配信されているチャンネルIDに対してブロードキャストするための接続を行った場合、downstreamの受信でメモリを消費し、Extensionが強制終了してしまうためです。（手持ちのiOS端末では50MBのメモリの上限値でした）

現状、iOSではdownstreamが発生しないようにiOS配信専用別チャンネルに配信し、他のクライアントではmultistream + iOS専用チャンネルの複数チャンネルを受信し、あたかも１つのチャンネル内でストリームを送受信しているかのように見せかけて回避しておりますが、`sendonly` パラメータにご対応いただけると `multistream` の１チャンネルのみで動画の送受信ができ、メンテナンスコストも下がり大変助かります。

不躾な要望で大変恐縮ですが、ご一考いただけると幸いです。

**Comment by voluntas** [comment]
@soudegesu SDK 側の対応は正式リリース後を考えていたのですが、優先度を上げて対応していきます。首を長くして、お待ちいただければと思います。

**Comment by soudegesu** [comment]
@voluntas ご確認いただきありがとうございます。大変ありがたいです。引き続きよろしくお願い致します。

**Comment by soudegesu** [comment]
ご対応いただきありがとうございます。
本issueはクローズさせていただきます。

**Comment by voluntas** [comment]
@soudegesu リリース時にご連絡すべきでした。大変失礼しました。他にもなにかありましたらお気軽にご相談いただければと思います。
