### ISSUE TITLE
ScreenCastでH.264を利用した配信を可能にする方法の共有

### ISSUE THREAD

**Issue by FromAtom** [shiguredo/sora-ios-sdk#34]
[ScreenCastSample](https://github.com/shiguredo/sora-ios-sdk-samples/tree/master/ScreenCastSample) にて

> 現在、サンプルアプリで使用している ReplayKit の実装都合上、 H.264 形式のビデオフォーマットを使用すると配信が途中で止まる不具合があります。 申し訳ありませんが、 ReplayKit と同時に使用する場合は、 VP9 などの他のビデオフォーマットでご利用ください。

といった記述がありますが、これを解決する方法が見つかりましたので共有いたします。

基本的な解決方法はiOSから得られる `CMSampleBuffer` をある程度まで小さくリサイズした上で、`MainStream.send(videoFrame:)` に渡せばよいです。`CMSampleBuffer` のリサイズ処理については、手前味噌ですが、[こちらの記事](https://fromatom.hatenablog.com/entry/2019/10/28/172628) を参考にして下さい。

サーバーがiOSクライアントに送信するSDPで、H.264のプロファイルレベルが3.1に設定されている場合、リサイズは1280x720より小さくするとうまく動きます。これは、このプロファイルレベルがサンプル数921,600までしかエンコードできない事に起因していると推測してます。そのため、正確には 1280x720 以下にリサイズするのではなく、921,600より少ないデータ数になるようにリサイズを行うことで、途中で止まることなく配信を行うことができました。

当然ですが、Broadcast Upload Extensionにおいても、同様に `CMSampleBuffer` のリサイズ処理を行うことで、H.264を利用した配信が可能であることを確認できました。

**Comment by szktty** [comment]
@FromAtom 貴重な情報提供ありがとうございます！

こちらでも試してサンプルコードに反映させたいと思います。
ご紹介頂いた方法を参考にして、映像フレームのサイズを変更する API を試験的に用意してみてもいいのかもしれませんね。検討してみます。

**Comment by FromAtom** [comment]
こちらのIssueは情報共有が目的で、今後議論する内容もないと思いますので、Closeさせていただきますね。

**Comment by voluntas** [comment]
@FromAtom 情報ありがとうございます、大変助かりました。
