### ISSUE TITLE
メディアチャネル除去の際にonAddMediaChannelが呼ばれる

### ISSUE THREAD

**Issue by tamiyoshi-naka** [shiguredo/sora-ios-sdk#36]
Sora SDK実装の際に発見したソースコード上の誤記と思われる部分です。

ファイル：
https://github.com/shiguredo/sora-ios-sdk/blob/develop/Sora/Sora.swift
行数：
152

にて、メディアチャネル除去でonAddMediaChannelが呼ばれている。
上の142行のメディアチャネル追加で同様に呼ばれているが、こちらは正しいようです。
ご確認いただけたら幸いです。

**Comment by szktty** [comment]
@tamiyoshi-naka ご報告ありがとうございます！

確かにここは `onRemoveMediaChannel` を呼ぶべきですね。修正リリース後に追ってご連絡致します。ありがとうございました！

**Comment by szktty** [comment]
@tamiyoshi-naka こちら、最新のリリース 2020.3 で修正しました。ご報告ありがとうございました。

**Comment by tamiyoshi-naka** [comment]
commit 46f69cd6695b428bddeb9d989133e8db2de7e86c にて修正されたことを確認しましたので、クローズします。
