### ISSUE TITLE
映像が真っ暗になる

### ISSUE THREAD

**Issue by BariYoshida** [shiguredo/sora-ios-sdk#37]
#32 で暫定対応して頂いたバイナリに差し替えてから、ユーザーから画面が真っ暗になるという問い合わせを多くいただく様になりました。
数ヶ月運用しておりますが、今までは同様の問い合わせはありませんでした。
弊社本番環境のログを見ると、"type":"error-closed"になって切断されているみたいで、弊社の開発環境だと再現が確認出来ていない状況です。
一度ご確認お願いできないでしょうか。
よろしくお願い致します。

---

Discord より抜粋

```
9割以上は正常に映ります
```

**Comment by voluntas** [comment]
@YoshidaArsaga 画面が真っ暗になるというのは映像を取得できていないという感じでしょうか。

error-closed はシグナリング周りで想定外の切断が発生している場合に起きている減少になります。

早急に確認してまいります。

**Comment by voluntas** [comment]
@YoshidaArsaga バイナリ差し替え前に利用して「申請が通っていた」際に利用していた Sora iOS SDK のバージョンをお教え頂けますでしょうか。

現在利用されてるのは 2020.1 のバイナリを切り替えたバージョンを利用されているという認識です。もし間違っていたらお教えいただければと思います。

**Comment by voluntas** [comment]
@YoshidaArsaga お手数ですが問題が起きた端末の iOS のバージョンをお教え頂けますでしょうか。2020.1 で WebSocket ライブラリを変更したことが影響したのでは？と見ています。

対策としては WebSocket ライブラリを古いものに戻し、iOS 13 以上は標準で搭載されている WebSocket ライブラリを利用する方向で考えています。

**Comment by BariYoshida** [comment]
@voluntas 
返信ありがとうございます。
SoraのiOS SDKバージョンは2.6.0です。

**Comment by BariYoshida** [comment]
@voluntas 
iOSは13.3.1です

**Comment by voluntas** [comment]
@YoshidaArsaga ありがとうございます。SDK 2.6.0 ということで、まずは WebSocket を昔のものに戻し、13.3.1 では iOS 標準のものを利用する仕組みを導入します。

古い WebSocket ライブラリは iOS 13 で不安定という issues が立っており、念の為の対応となります。

**Comment by BariYoshida** [comment]
@voluntas 
ありがとうございます。そのバージョンで様子見れればと思います。

**Comment by voluntas** [comment]
問題を整理させていただきます。

- iOS SDK 2.6.0 + バイナリ差し替え無し
   - 問題なし、ただし審査が通らない
- iOS SD 2.6.0 + バイナリ差し替え有り
   - 映像が真っ暗になる場合がある、９割は正常に映る

**Comment by voluntas** [comment]
Sora iOS SDK 2.6.0 とバイナリ差し替えありで quickstart にて検証を行っておりますが、いまの所特に問題がでてはいません。

**Comment by voluntas** [comment]
Sora 側のロクを確認したところ、配信自体も特に問題なくされていたようです。表示の問題かと思い、 iOS SDK 2020.3 や 2.6.0 (バイナリ入れ替え) で quickstart を利用して検証しましたが再現しませんでした。Sora 側にも怪しいログは出ませんでした。

**Comment by voluntas** [comment]
iOS SDK 2020.3 で再度確認の方をお願いできればと思います。

**Comment by BariYoshida** [comment]
@voluntas 
お世話になっております。
弊社環境で再現せず、原因がまだ分かっておりませんが、2020.3にアップデートしてもまだ映像が真っ暗で何も映らなくなると言う問い合わせを複数いただいております。
取り急ぎ報告のみとなりますが、よろしくお願い致します。

**Comment by voluntas** [comment]
@YoshidaArsaga ご報告ありがとうございます。弊社側でも再現を試みます。お手数をおかけしますが映像が真っ暗で何も映らなくなる問題が発生したときの Sora 側のログを Connection ID を含めていただけますでしょうか。 (ログアップローダ側へお願いできればと思います)

複数あるとの事でしたので、複数の Connection ID をお教えいただけると助かります。

**Comment by voluntas** [comment]
@YoshidaArsaga 弊社側で色々と検証をしてまいりましたが、再現が一切しない状況です。

ほぼ御社と同じ環境でサーバ側でパケロスや遅延なども発生させた状態で iOS 側で確認しておりますが、問題なく視聴できている状況です。

現時点で弊社側でやれることがない状況です ... 。Sora のログからもクライアント側が異常終了したように見えるため、iOS アプリ側で何が起きてるかなどのログを頂ければ助かります。

また "ユーザーから画面が真っ暗になる" こちらについてもう少し詳細をいただければと思います。

- 接続した当初は映像が見えていたが、突然見えなくなったのか
   - 突然見えなくなった場合はどのような映像だったのか
- 接続した当初から映像が見えていないのか

ご確認のほどよろしくお願いいたします。

**Comment by BariYoshida** [comment]
@voluntas 
こちらの問題ですが、ネットワークの切り替えが起きた際に起こるのではと言う結論になり、その際に再接続をする運びになりました。
それを実装したものをリリースして様子をみようと思います。
お騒がせしました。
ご対応いただき感謝しております。
ありがとうございました。

**Comment by voluntas** [comment]
@YoshidaArsaga 問題解決とのことでなによりです。
