### ISSUE TITLE
ストリームの状態変換のイベントハンドリングについて

### ISSUE THREAD

**Issue by koyama** [shiguredo/sora-ios-sdk#4]
https://sora.shiguredo.jp/ios-sdk-doc/api.html#connectionerror
にて、エラーハンドリング用のイベントはご用意いただいていますが、配信側の映像が停止したり、ストリームデータの取得が失敗したりした場合、映像を表示することができなくなると思いますが、そういった映像表示に支障がでるような状態変化について、イベントハンドリングや情報取得の方法はありますでしょうか？

もしあるようでしたら手法をご教示いただきたいです

**Comment by voluntas** [comment]
@koyama こちらの SDK には接続や切断といったもの以外で、映像がおかしいや映像が届かないといったエラーハンドリングのイベントは残念ながらありません。

これは WebRTC API がそのような仕組みを持っていないためです。

**Comment by voluntas** [comment]
@koyama こちら問題ありませんでしょうか？ 一度閉じさせていただきます。問題あれば reopen か新規に issues を開いていただければと思います。
