### ISSUE TITLE
VideoViewのサイズ変更への追従

### ISSUE THREAD

**Issue by koyama** [shiguredo/sora-ios-sdk#5]
受信側で視聴中にフルスクリーン等の表示変更をしたいと思っています。
アプリ側でVideoViewのサイズを変更したときにレンダリングされる映像のサイズも変更したいのですが、それができるAPIはありますか？

**Comment by voluntas** [comment]
@koyama VideoView のサイズが変更されたとき、レンダリングされる映像のサイズが変更されるかどうかが弊社側では未検証です。そのため御社側にて確認をお願いできますでしょうか。

**Comment by koyama** [comment]
弊社で確認したところ変更されないです

**Comment by szktty** [comment]
@koyama 検証ありがとうございました。 VideoView のサイズ変更については 1.1.0 で対応する予定です。

**Comment by koyama** [comment]
ありがとうございます
内容承知いたしました
