### ISSUE TITLE
ws,wss以外での通信について

### ISSUE THREAD

**Issue by koyama** [shiguredo/sora-ios-sdk#6]
soraサーババージョン1.1.0の変更点にて、

[CHANGE] Sora サーバーの URL のプロトコルが ws または wss 以外であればエラーにする
とありますが、こちら、
https://sora.shiguredo.jp/ios-sdk-doc/quickstart.html
https://sora.shiguredo.jp/doc/SIGNALING.html
等を見る限りwssでなければならない旨記載がないのですが、既にwss以外のプロトコルでの実装していることへの対処はなされないものなのでしょうか

**Comment by voluntas** [comment]
@koyama Sora のシグナリングで利用している WebSocket の正式な URL Schema は ws と wss のため、本来は http や https が使えてはいけないところを使えるようにしていたための修正となります。

大変もうしわけないですが、既存の URL Schema を ws または wss に修正頂ければと思います。

蛇足ではありますが、実際 JavaScript で WebSocket を利用しようした時に http や https を使用とした場合はエラーとなります。

![2017-06-02 16 46 12](https://cloud.githubusercontent.com/assets/15551/26716074/033bab14-47b3-11e7-94c4-200b4e837b07.png)

**Comment by koyama** [comment]
ご返答ありがとうございます
内容承知いたしましたので、wssにて進めるようにさせていただきます
当課題は完了で構いません
