### ISSUE TITLE
Swift4への対応時期は決まっていますでしょうか？

### ISSUE THREAD

**Issue by iPre-Innovate** [shiguredo/sora-ios-sdk#8]

**Comment by voluntas** [comment]
@iPre-Innovate Swift 4 への対応ですが現在絶賛対応中で 2017 年 11 月中にはリリースできるかともいます。もうしばらくお待ちいただければと思います。

もし早めに確認したいとのことであれば、こちらのブランチで試すことは可能です。
https://github.com/shiguredo/sora-ios-sdk/commits/develop

Swift 4 に対応しましたらこの issue でお知らせいたします。

**Comment by voluntas** [comment]
@iPre-Innovate おまたせしておりました、Swift 4 対応である 2.0 を本日リリースしました。

2.0 に対応したドキュメントもリリースいたしましたのでご確認いただければと思います。
https://sora.shiguredo.jp/ios-sdk-doc/index.html
